-- 코드를 입력하세요
SELECT
    O.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRICE*SUM(O.AMOUNT) AS TOTAL_SALES
FROM
    FOOD_ORDER O
Join
    FOOD_PRODUCT P
ON
    O.PRODUCT_ID = P.PRODUCT_ID
WHERE
    O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY
    P.PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC,
    P.PRODUCT_ID ASC;
   
